apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid-19-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid-19-client
  template:
    metadata:
      labels:
        app: covid-19-client
    spec:
      containers:
        - name: covid-19-client
          image: localhost:32000/covid-19-client:1.8.0-beta
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: covid-19-client-service
spec:
  type: NodePort
  selector:
    app: covid-19-client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
      protocol: TCP